config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get "users/signin", to: "users/sessions#new", as: :new_user_session_path
  end
  mount Notifications::Engine => "/notifications"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  else
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  
  get 'products', to: 'products#index'
  get 'products/:id', to: 'products#show', as: 'product'
  get 'products/:id/like', to: 'products#like', as: 'like'
  # get '/stores/:store_id/products/:id', to: 'products#show', as: 'product'
  get 'products/categories/:id', to: 'categories#show', as: 'category'
  
  get 'orders', to: 'orders#index'
  
  resources :carts, only: [:index, :destroy]
  resources :tendances
  resources :users do
    resources :accounts do
      resources :transactions
    end
    resources :favorites
    resources :orders, only: [:index]
    resources :chats do
      resources :messages
    end
    resources :orders, only: [:index, :show, :destroy]
    resources :carts, only: [:index, :destroy] do
      resources :orders, only: [:create, :destroy]
    end
  end
  resources :stores do
    resources :orders, only: [:index, :show, :update, :destroy]
    resources :comments
    resources :chats do
      resources :messages
    end
    resources :products do
      resources :stocks
      resources :line_items, only: [:create]
      resources :bids, except: [:edit] do
        resources :offers, only: [:new, :create, :edit, :update]
      end
      resources :comments
    end
  end

  #Historic of offers by user
  get 'profile/:user_id/offers' => "offers#historic", as: "user_offers_historic"
  #Details of offers by user
  get 'profile/:user_id/offers/:id' => "offers#details", as: "user_offers_offer_historic_details"
  
  # For historic of bids
  get '/stores/:store_id/bids/' => "bids#historic", as: "store_bids_historic"
  # For historic of bid details
  get '/stores/:store_id/bids/:id' => "bids#details", as: "store_bids_bid_historic_details"

  # get '/stores/:store_id/products/:id', to: 'products#show'
  get 'bids', to: 'bids#index'

  # Validate/Reject order
  put 'stores/:store_id/orders/:id/validated' => "orders#validate_order", as: "validate_order"
  put 'stores/:store_id/orders/:id/rejected' => "orders#reject_order", as: "reject_order"
  
  resources :line_items, only: [:create]
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  delete 'line_items/:id' => "line_items#destroy", as: "line_item_delete"
  resources :profiles, only: %i[show edit update]

  root to: "home#index"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product

  scope :find_user_favorite, ->(user,product){ where(user_id:user.id, product_id:product.id, still_favorites?: true)}
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user
      if current_user.first_name == nil && current_user.town == nil && current_user.city == nil
        redirect_to edit_profile_path(current_user)
      end 
    end
    @favorites = Favorite.where(user_id: current_user.id, still_favorites?: true)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<div class="mb-12 relative">
  <div class="absolute top-2 right-3">
    <a href="<%=like_path(favorite.product, user:current_user, source:'favorites') %>">
        <i class="fas fa-heart text-2xl text-red-500"></i>
    </a>
  </div>
  <div class="h-64 w-full overflow-hidden">
    <% if favorite.product.product_backgrounds.attached? %>
      <%=image_tag favorite.product.product_backgrounds[0], class:'h-64 w-full object-cover'%>
    <%else%>
      <%=image_tag 'default_product_image.png', class:'h-64 w-full object-cover'%>
    <% end %>
  </div>
  <a href='<%= product_path(favorite.product) %>' class="w-full h-full">
    <div class="py-2 flex items-center justify-between ">
      <div class="w-32">
        <p class=" font-medium text-lg"><%=favorite.product.name%></p>
        <p class=" font-normal text-sm py-1"><%=favorite.product.price%> FCFA</p>
      </div>
      <%if favorite.product.store.user != current_user%>
        <div class="w-2/5">
          <%if current_user %>
            <a href="<%= store_product_line_items_path(favorite.product.store, favorite.product) %>" data-method="POST" class="px-5 py-2 bg-red-600 text-white">
              Acheter
            </a>
          <% else %>
            <a href="<%= new_user_session_path %>" class="px-5 py-2 bg-red-600 text-white">
              Acheter
            </a>
          <% end %>
        </div>
      <% end %>
    </div>
  </a>
</div>

app/views/favorites/index.html.erb
<style>
  .min-height{
    min-height:35rem
  }
</style>
<div class="py-5 min-height px-5">
  <div class=" py-3 px-3 border-b border-gray-200">
    <p class="text-4xl">Mes favoris</p>
  </div>
  <div class="py-3 px-3 grid grid-cols-5 gap-2">
    <%=render partial: 'favorite', collection:@favorites%>
  </div>
</div>

<% content_for :banners do %>
  <%=render 'shared/banners'%>
<% end %>

<% content_for :footer do %>
  <%=render 'shared/footer'%>
<% end %>