config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get "users/signin", to: "users/sessions#new", as: :new_user_session_path
  end
  mount Notifications::Engine => "/notifications"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  else
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  
  get 'products', to: 'products#index'
  get 'products/:id', to: 'products#show', as: 'product'
  get 'products/:id/like', to: 'products#like', as: 'like'
  # get '/stores/:store_id/products/:id', to: 'products#show', as: 'product'
  get 'products/categories/:id', to: 'categories#show', as: 'category'
  
  get 'orders', to: 'orders#index'
  
  resources :carts, only: [:index, :destroy]
  resources :tendances
  resources :users do
    resources :accounts do
      resources :transactions
    end
    resources :favorites
    resources :orders, only: [:index]
    resources :chats do
      resources :messages
    end
    resources :orders, only: [:index, :show, :destroy]
    resources :carts, only: [:index, :destroy] do
      resources :orders, only: [:create, :destroy]
    end
  end
  resources :stores do
    resources :orders, only: [:index, :show, :update, :destroy]
    resources :comments
    resources :chats do
      resources :messages
    end
    resources :products do
      resources :stocks
      resources :line_items, only: [:create]
      resources :bids, except: [:edit] do
        resources :offers, only: [:new, :create, :edit, :update]
      end
      resources :comments
    end
  end

  #Historic of offers by user
  get 'profile/:user_id/offers' => "offers#historic", as: "user_offers_historic"
  #Details of offers by user
  get 'profile/:user_id/offers/:id' => "offers#details", as: "user_offers_offer_historic_details"
  
  # For historic of bids
  get '/stores/:store_id/bids/' => "bids#historic", as: "store_bids_historic"
  # For historic of bid details
  get '/stores/:store_id/bids/:id' => "bids#details", as: "store_bids_bid_historic_details"

  # get '/stores/:store_id/products/:id', to: 'products#show'
  get 'bids', to: 'bids#index'

  # Validate/Reject order
  put 'stores/:store_id/orders/:id/validated' => "orders#validate_order", as: "validate_order"
  put 'stores/:store_id/orders/:id/rejected' => "orders#reject_order", as: "reject_order"
  
  resources :line_items, only: [:create]
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  delete 'line_items/:id' => "line_items#destroy", as: "line_item_delete"
  resources :profiles, only: %i[show edit update]

  root to: "home#index"
end

app/models/store.rb
class Store < ApplicationRecord
  validates :name, 
            :description,
            :city,
            :town,presence: true
  belongs_to :user
  has_many :carts, :dependent => :destroy

  has_many :orders, through: :carts ,:dependent => :destroy
  has_many :products, :dependent => :destroy

  has_many :comments, through: :products, :dependent => :destroy
  
  has_one_attached :background, :dependent => :destroy
  has_many :chats, :dependent => :destroy
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if current_user
      if current_user.first_name == nil && current_user.town == nil && current_user.city == nil
        redirect_to edit_profile_path(current_user)
      end 
    end
    @stores = Store.all
  end

  def new
    @user = current_user
    @store = Store.new(user_id: params[:user_id])
  end

  def show
    if current_user
      if current_user.first_name == nil && current_user.town == nil && current_user.city == nil
        redirect_to edit_profile_path(current_user)
      end 
    end
    id = params[:id]
    @store = Store.find(id)
    @store_products = @store.products
    @comments = Comment.joins(:product).where('products.store_id = ?', current_user.store.id) if current_user && current_user.store
  end

  def create
    @store = current_user.build_store(store_params)
    if @store.save
      redirect_to store_path(@store), notice: 'Le store à été créé avec succès!'
    else
      flash[:error] = "Le store ne peut être créé"
      render 'new'
    end
  end

  def edit
    @store = current_user.store
  end

  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
      redirect_to profile_path(current_user), notice: 'Information de la boutique mis à jour'
    else
      flash[:error] = 'Le store ne peut être mis à jour!'
      render 'edit'
    end
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    redirect_to profile_path(current_user), notice: 'Boutique supprimée'
  end


  private 

  def user
    @user ||= User.find(params[:user_id])
  end
  
  def store_params
    params.require(:store).permit(
      :name,
      :description,
      :city,
      :town,
      :background
    )
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_comment.html.erb
<div class="w-full flex bg-gray-100 rounded items-start overflow-scroll">
  <div class="w-20 h-20">
    <% if comment.product.product_backgrounds.attached? %>
      <%= image_tag comment.product.product_backgrounds[0], class:'m-0 rounded-full h-full w-full '%>
    <%else%>
      <%=image_tag 'default_product_image.png', class:'h-full w-full object-cover'%>
    <% end %>
  </div>

  <div class="ml-2">
    <p class="text-sm"><strong>Produit : </strong><%= comment.product.name%>, <%= comment.product.price%> Fcfa</p>
    <p class="text-sm"> <strong> De : </strong> <%= comment.user.first_name%></p>
    <p class="text-sm"> <strong> Avis : </strong> <%= comment.comment%></p> 
  </div> 
</div> <br>

app/views/stores/_form.html.erb
<style>
  .h-99{
    height:35rem
  }
</style>

<%= form_with model: [store], data:{controller: 'img-display-on-create-store'} do |form|%>
  <div class="flex justify-between">
    <div class="w-3/5 px-3">
      <div class="">
        <label class="flex justify-center py-1 items-center ease-linear transition-all duration-150 bg-gray-300 text-gray-600 hover:bg-gray-400 hover:text-gray-700 w-2/5  rounded-md mx-auto mb-3">
          Choisir une image
          <%= form.file_field :background,accept:'.png, .jpeg, .fpg, .svg, .jpg',class:'hidden',data: {'img-display-on-create-store-target': 'imgGetter', action:'change->img-display-on-create-store#displayImage'} %>
        </label>
        <div class="flex justify-center mx-auto items-center h-96 w-full overflow-hidden mt-5" data-img-display-on-create-store-target='divDisplaying'></div>
      </div>
    </div>
    <div class="w-2/5 px-5 border-l border-gray-100 py-10">
      <div>
        <%= form.text_field :name,placeholder:'Nom',class:'bg-gray-100 px-2 w-4/5 py-2 rounded mb-4 outline-none' %>
        <% if store.errors[:name] %>
          <span style='color: red'><%= store.errors[:first_name][0] %></span>
        <% end %>
      </div>  
      <div>
        <%= form.text_area :description,placeholder:'Description',class:'bg-gray-100 px-2 w-4/5 py-2 rounded mb-4 outline-none' %>
      </div>
      <% if store.errors[:description] %>
        <span style='color: red'><%= store.errors[:description][0] %></span>
      <% end %>
      <div>
        <%= form.text_field :city,placeholder:'Ville',class:'bg-gray-100 px-2 w-4/5 py-2 rounded mb-4 outline-none'  %>
      </div>
      <% if store.errors[:city] %>
        <span style='color: red'><%= store.errors[:city][0] %></span>
      <% end %>
      <div>
        <%= form.text_field  :town,placeholder:'Commune ou Quartier',class:'bg-gray-100 px-2 w-4/5 py-2 rounded mb-4 outline-none'  %>
      </div>
      <% if store.errors[:town] %>
        <span style='color: red'><%= store.errors[:town][0] %></span>
      <% end %>
      <%= form.submit submit, class:"bg-red-600 text-white hover:bg-red-700 font-bold py-2 px-4 rounded w-4/5" %>
    </div>
  </div>
<% end %>

app/views/stores/_product.html.erb
<a href='<%= store_product_path(product.store,product) %>' class="mb-2">
  <% if product.product_backgrounds.attached? %>
    <%= image_tag product.product_backgrounds[0], class:'m-0 h-40 w-full object-cover '%>
  <%else%>
    <%=image_tag 'default_product_image.png', class:'h-40 w-full object-cover'%>
  <% end %>
  <div class="py-1 flex items-center justify-center">
    <div class="w-full">
      <p class=" font-medium text-md"><%=product.name%></p>
      <p class=" font-normal text-xs py-1"><%= number_with_delimiter(product.price, :delimiter => '.')%> FCFA</p>
    </div>
  </div>
</a>

app/views/stores/_store.html.erb
<div class="w-full max-w-sm mx-auto rounded-md shadow-md overflow-hidden">
  <a href="<%= store_path(store)%>">
    <div class="flex items-end justify-end h-56 w-full overflow-none">
      <% if store.background.persisted? %>
        <%= image_tag store.background, class:'object-cover  h-64 w-full '%>
      <%else%>
        <%=image_tag 'App-Store.jpg', class:'h-64 w-full object-cover'%>
      <% end %>
    </div>
    <div class="px-5 py-3">
    <h3 class="text-gray-700 uppercase"><%= store.name %></h3>
    </div>
  </a>
</div>

app/views/stores/create.html.erb
<h1>stores#create</h1>

app/views/stores/destroy.html.erb
<h1>Stores#destroy</h1>

app/views/stores/edit.html.erb
<div>
  <h1 class="text-4xl font-medium text-gray-700 px-3 py-5">Stores Modification</h1>
  <%= render partial: 'form', locals: {user: @user, store: @store, submit: 'Mettre a jour'}%>
</div>

<% content_for :banners do %>
  <%=render 'shared/banners'%>
<% end %>

<% content_for :footer do %>
  <%=render 'shared/footer'%>
<% end %>

app/views/stores/index.html.erb
<div class="bg-white">
  <main class="my-8">
      <div class="container mx-auto px-6">
          <div class="grid gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mt-6">
              <%=render partial: 'store',collection:@stores%>
          </div>

          
      </div>
  </main>
</div>

<% content_for :banners do %>
  <%=render 'shared/banners'%>
<% end %>
<% content_for :footer do %>
  <%=render 'shared/footer'%>
<% end %>

app/views/stores/new.html.erb
<div>
  <h1 class="text-4xl font-medium text-gray-700 px-3 py-5">Créer un Store</h1>
  <%= render partial: 'form', locals: {user: @user, store: @store, submit: 'Créer votre store'}%>
</div>

<% content_for :banners do %>
  <%=render 'shared/banners'%>
<% end %>

<% content_for :footer do %>
  <%=render 'shared/footer'%>
<% end %>

app/views/stores/show.html.erb
<style>
.h-100 {
  min-height: 28rem/* 384px */;
}
.h-36r{
  height:36rem
}
</style>

<div class="min-h-screen flex overflow-hidden">
  <div class="<%=current_user == @store.user ? 'w-full overflow-hidden' : 'w-full overflow-hidden'%>">
    <div class="flex py-10 justify-between items-center w-4/5 mx-auto pr-5">
      <p class="text-4xl font-medium text-center">
        <%= current_user == @store.user ? 'Ma boutique' : "#{@store.name}"%>
      </p>
      <p class="text-4xl font-medium text-center ml-16">
      </p>
      <%if current_user %>
        <% if current_user && @store.user.id != current_user.id %>
          <a href="<%= current_user ? new_store_chat_path(@store): new_user_session_path %>" class="bg-green-600 text-white px-5 py-2 rounded">
            Ecrire
            <i class="fad fa-paper-plane"></i>
          </a>
        <%else%>
          <div class='flex justify-center items-center'>
            <%= link_to 'Supprimer mon store', store_path(@store), data:{confirm: 'Etes vous sur de vouloir supprimer votre compte? '} ,method: :delete, class:'bg-red-600 text-white px-5 py-2 mr-2 font-medium rounded' %>
            <%= link_to 'Ajouter un article', new_store_product_path(@store), class:'bg-green-600 text-white px-5 py-2 font-medium rounded' %>
            <%= link_to 'Voir les avis', store_comments_path(@store), class:'bg-green-600 text-white px-5 py-2 font-medium rounded ml-2' %>
          </div>
        <% end %>
      <% else %>
        <a href="<%= new_user_session_path %>" class="bg-green-600 text-white px-5 py-2 rounded">
          Ecrire
          <i class="fad fa-paper-plane"></i>
        </a>
      <% end %>
    </div>
    <div class='grid grid-cols-4 gap-1 h-100 w-4/5 my-0 mx-auto'>
      <%=render partial:'product', collection: @store_products%>
    </div>
    <%if current_user && current_user.store == @store%>
      <div class="w-full py-10"> 
        <a href="<%= bids_path %>">
          <p class="text-3xl ml-20">Mes actions</p>
        </a>
        <div class="w-full flex justify-evenly items-center py-5">
          <a href="<%= store_orders_path(@store) %>" class="text-center px-3">
            <%=image_tag 'icons8-deliver-food-100 (1).png', class:'w-16 h-16 mx-auto'%>
            <p class="py-8 text-lg">Commandes</p>
          </a>
          <a href="<%=store_bids_historic_path(@store)%>" class="text-center px-3">
            <%=image_tag 'icons8-judge-60 (1).png', class:'w-16 h-16'%>
            <p class="py-8 text-lg">Historiques des enchères</p>
          </a>
        </div>
      </div>
    <% end %>
  </div>
</div>


<% content_for :banners do %>
  <%=render 'shared/banners'%>
<% end %>

<% content_for :footer do %>
  <%=render 'shared/footer'%>
<% end %>

app/views/stores/update.html.erb
<h1>stores#update</h1>