config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get "users/signin", to: "users/sessions#new", as: :new_user_session_path
  end
  mount Notifications::Engine => "/notifications"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  else
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  
  get 'products', to: 'products#index'
  get 'products/:id', to: 'products#show', as: 'product'
  get 'products/:id/like', to: 'products#like', as: 'like'
  # get '/stores/:store_id/products/:id', to: 'products#show', as: 'product'
  get 'products/categories/:id', to: 'categories#show', as: 'category'
  
  get 'orders', to: 'orders#index'
  
  resources :carts, only: [:index, :destroy]
  resources :tendances
  resources :users do
    resources :accounts do
      resources :transactions
    end
    resources :favorites
    resources :orders, only: [:index]
    resources :chats do
      resources :messages
    end
    resources :orders, only: [:index, :show, :destroy]
    resources :carts, only: [:index, :destroy] do
      resources :orders, only: [:create, :destroy]
    end
  end
  resources :stores do
    resources :orders, only: [:index, :show, :update, :destroy]
    resources :comments
    resources :chats do
      resources :messages
    end
    resources :products do
      resources :stocks
      resources :line_items, only: [:create]
      resources :bids, except: [:edit] do
        resources :offers, only: [:new, :create, :edit, :update]
      end
      resources :comments
    end
  end

  #Historic of offers by user
  get 'profile/:user_id/offers' => "offers#historic", as: "user_offers_historic"
  #Details of offers by user
  get 'profile/:user_id/offers/:id' => "offers#details", as: "user_offers_offer_historic_details"
  
  # For historic of bids
  get '/stores/:store_id/bids/' => "bids#historic", as: "store_bids_historic"
  # For historic of bid details
  get '/stores/:store_id/bids/:id' => "bids#details", as: "store_bids_bid_historic_details"

  # get '/stores/:store_id/products/:id', to: 'products#show'
  get 'bids', to: 'bids#index'

  # Validate/Reject order
  put 'stores/:store_id/orders/:id/validated' => "orders#validate_order", as: "validate_order"
  put 'stores/:store_id/orders/:id/rejected' => "orders#reject_order", as: "reject_order"
  
  resources :line_items, only: [:create]
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  delete 'line_items/:id' => "line_items#destroy", as: "line_item_delete"
  resources :profiles, only: %i[show edit update]

  root to: "home#index"
end

app/views/shared/_banners.html.erb
<nav class="w-full overflow-x-hidden top-0 p-3 flex justify-between items-start">
  <span class="w-1/6 px-2">
    <a href='<%=root_path %>' class="w-full h-14 flex px-2 justify-center overflow-hidden">
      <%=image_tag 'Group 3.png', class:'w-full h-12 '%>
    </a>
  </span>
  <div class="w-4/6">
    <%=yield :search_bar%>
    <span class="w-full">
      <div class="flex items-center justify-evenly pt-2">
        <a href='<%= products_path %>' class='font-semibold text-xl'>Tous les produits</a>
        <a href='<%= stores_path %>' class='font-semibold text-xl'>Stores</a>
        <a href='<%= tendances_path%>' class='font-semibold text-xl'>Tendances</a>
        <a href='<%= bids_path %>' class='font-semibold text-xl'>Enchères</a>
      </div>
    </span>
  </div>
  <span class='w-1/6 flex items-center justify-evenly pt-2'>

    <% if current_user %>

      <a href='<%= user_carts_path(current_user) %>' class="relative flex items-stretch">
        <i class="fal fa-shopping-cart text-2xl"></i>
        <% if current_user.carts.where(validated: false).count > 0 %>
          <span class="w-3 h-3 bg-red-600 rounded-full absolute -top-1 -right-1">
          </span>
        <% end %>        
      </a>

      <a href='<%=user_favorites_path(current_user) %>'>
        <i class="fal fa-heart text-2xl"></i>
      </a>

      <a href='<%= user_chats_path(current_user)%>' class="relative flex items-stretch">
        <i class="fal fa-comment-alt text-2xl"></i> 
        <% if Notification.all_unread_user(current_user.id).length >0 %>
          <span class="w-3 h-3 bg-red-600 rounded-full absolute -top-1 -right-1">
          </span>
        <% end %>
      </a>

    <% end %>
    <a href="<%= current_user == nil ? new_user_session_path : profile_path(current_user) %>" >
      <i class="fal fa-user text-2xl"></i>
    </a>
  </span>
</nav>

app/views/shared/_bid_cart.html.erb
<div class="bg-white shadow-md border border-gray-200 rounded-lg max-w-sm mt-3">
  <a href="<%= store_product_bid_path(bid.product.store, bid.product, bid) %>">
    <% if bid.product.product_backgrounds.attached? %>
      <%= image_tag bid.product.product_backgrounds[0], class:'object-cover' %>
    <% else %>
      <%= image_tag 'default_product_image.png', class:'object-cover' %>
    <% end %>
  </a>
  <div class="p-5">
    <a href="#">
      <h5 class="text-gray-900 font-bold text-2xl tracking-tight mb-2"><%= bid.product.name %></h5>
    </a>
    <p class="font-normal text-gray-700 mb-3"><%= bid.product.description %></p>
    <a class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-3 py-2 text-center inline-flex items-center" href="<%= store_product_bid_path(bid.product.store, bid.product, bid) %>">
      Détails de l'enchère
    </a>
  </div>
</div>

app/views/shared/_cart.html.erb
<hr>
<div class="mt-5 mb-20">
  <h2 class="font-bold text-2xl mt-3 mb-5 text-center">Panier du store "<%= cart.store.name %>"</h2>
  <% cart.line_items.each do |item| %>
    <%= render partial: "shared/cart_item", locals: { item: item } %>
  <% end %>
  <div class="flex w-1/2 mt-5 mx-auto justify-between text-center justify-items-center items-center">
    <h2 class="font-bold text-2xl">Prix total: <%= cart.total_price %> FCFA</h2>
    <div class="mt-5">
      <a href="<%= user_cart_path(current_user, cart) %>", data-method="DELETE", data-confirm="Êtes vous sûr?">
        <i class="fas fa-trash text-xl"></i>
      </a>
      <span>
        <%= link_to "Valider votre panier", user_cart_orders_path(current_user, cart), method: :post, data: { confirm: "Voulez vous valider votre panier?" }, class:"bg-red-600 m-5 p-5 rounded text-white mt-5" %>
      </span>
    </div>
  </div>
</div>

app/views/shared/_cart_item.html.erb
<div class="w-3/4 mx-auto">
  <li class="py-3 flex justify-center">
    <div class="flex-shrink-0 w-24 h-24 border border-gray-200 rounded-md overflow-hidden">
      <% if item.product.product_backgrounds.attached? %>
        <%= image_tag item.product.product_backgrounds[0], class:'object-cover' %>
      <% else %>
        <%= image_tag 'default_product_image.png', class:'object-cover' %>
      <% end %>
    </div>
    <div class="ml-4 flex-1 flex flex-col">
      <div>
        <div class="flex justify-between text-base font-medium text-gray-900">
          <h3>
            <a href="#">
              <%= link_to "#{item.product.name}", store_product_path(item.product.store, item.product) %>
            </a>
          </h3>
          <p class="ml-4">
            <%= number_with_delimiter( item.total_price, :delimiter => '.') %> FCFA
          </p>
        </div>
        <p class="mt-1 text-sm text-gray-500">
          <%= item.product.description %>
        </p>
      </div>
        <div class="flex justify-between items-center">
          <div class="flex flex-row h-10 w-2/3 rounded-lg relative bg-transparent mt-1">
            <a href="<%= line_item_reduce_path(item) %>" data-method="POST">
              <button data-action="decrement" class=" bg-gray-300 text-gray-600 hover:text-gray-700 hover:bg-gray-400 h-full w-20 rounded-l cursor-pointer outline-none">
                <span class="m-auto text-2xl font-thin">−</span>
              </button>
            </a>

          <div class="flex w-12 justify-center items-center"><%= item.quantity %></div>
            <a href="<%= line_item_add_path(item) %>" data-method="POST">
              <button data-action="increment" class="bg-gray-300 text-gray-600 hover:text-gray-700 hover:bg-gray-400 h-full w-20 rounded-r cursor-pointer">
                <span class="m-auto text-2xl font-thin">+</span>
              </button>
            </a>
          </div>

          <div class="">
            <button type="button" class="font-medium text-red-600 hover:text-red-500">
              <a href="<%= line_item_delete_path(item) %>" data-method="DELETE" data-confirm="Êtes vous sûr?" class="m-3">
              Supprimer 
              </a>
            </button>
          </div>
        </div>
      </div>
    </div>
  <hr>
  </li>
</div>

app/views/shared/_flashes.html.erb
<style>
  .type-alert {
    background:#F8503A;
    width:25%;
    height:60px;
    display:flex;
    justify-content:center;
    align-items:center;
    background-opacity:0.8;
    color:#fff
  }
  .type-success {
    background:#579E60;
    width:25%;
    height:60px;
    display:flex;
    justify-content:center;
    align-items:center;
    background-opacity:0.8;
    color:#fff
  }
  .type-notice{
    background:#4190C8;
    width:25%;
    height:60px;
    display:flex;
    justify-content:center;
    align-items:center;
    background-opacity:0.8;
    color:#fff
  }
</style>


<div class="absolute flex w-full justify-center top-5 mt-10 z-10 " id='flash'>
  <% flash.each do |type, msg|%>
    <div class="type-<%=type%>">
      <%= msg %>
    </div>
  <% end %>
</div>

<script>
  setTimeout(function(){
    document.getElementById('flash').remove()
  }, 6000)
</script>

app/views/shared/_navbar.html.erb
<header class="w-full bg-gray-800 p-4 flex justify-between items-center">
  <nav class="flex items-center">
    <% if current_user %>
      <%= current_user.email %>
    <% end %>
    <h3 class="text-white">
        <%= link_to 'Jokou', root_path %>
      </h3>
  </nav>
  <div class="text-white">
    <% if user_signed_in? %>
      <h3>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      </h3>
    <% end %>
  </div>
  <div class="text-white">
    <h3>
      <%= link_to 'Sign In', new_user_session_path %>
    </h3>
  </div>
  <div class="text-white">
    <h3>
      <%= link_to 'Register', new_user_registration_path%>
    </h3>
  </div>

  <div class="text-white">
    <h3>
      <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, method: :post %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, method: :post %>
    </h3>
  </div>
</header>

app/views/shared/_order.html.erb
<div class="flex flex-col text-2xl font-bold mt-5 items-center">
  <div class="flex bg-gray-200 rounded p-5 items-center w-3/4 justify-around">
    <h2>
      <%= link_to "Commande ##{order.id[0,7].upcase}", store_order_path(order.cart.store, order) %>
    </h2>
    <h2>
      Prix : <%= number_with_delimiter( order.cart.total_price, :delimiter => '.') %> XOF
    </h2>
    <h2>
      Nombre de produits (<%= order.cart.line_items.count %>)
    </h2>
    <div>
      <a href="<%= reject_order_path(order.cart.store, order) %>" data-method="DELETE", data-confirm="Supprimer la commande ?">
        <i class="fad fa-times-circle text-3xl text-red-500"></i>
      </a>
    </div>
  </div><br>
</div>

app/views/shared/_order_page.html.erb
<hr>
<h2 class="text-center font-bold text-3xl my-5">
  Commande  #<%= "#{order.id[0,7].upcase}" %>
</h2>
<% order.cart.line_items.each do |item| %>
<div class="">
  <div class="container mx-auto p-3 max-w-screen-lg">
    <div class="flex justify-between flex-wrap lg:justify-center">
      <div class="bg-gray-200 rounded shadow w-full lg:w-2/4">
        <div class="w-full flex justify-around bg-orange-200 py-6">
          <div>
            <% if item.product.product_backgrounds.attached? %>
              <%= image_tag item.product.product_backgrounds[0], class:'object-cover w-28 h-auto' %>
            <% else %>
              <%= image_tag 'default_product_image.png', class:'object-cover w-28 h-auto' %>
            <% end %>
          </div>
          <div class="flex flex-col justify-around">
            <div class='text-xl text-right font-bold '>
              <%= item.product.name %>
            </div>
            <div class='text-xl text-right font-bold'>
              x<%= item.quantity %>
            </div>
            <div class='text-xl text-right font-bold'>
              <%= number_with_delimiter( item.total_price, :delimiter => '.')  %> FCFA
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<h2 class="text-center font-bold text-3xl m-5">
  Prix total : <%= number_with_delimiter( order.cart.total_price, :delimiter => '.') %> FCFA
</h2>

app/views/shared/_order_table.html.erb
<div class='px-10'>
  <table class="w-full">
        <thead>
          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
            <th class="px-4 py-3">ID</th>
            <th class="px-4 py-3">Nom des clients</th>
            <th class="px-4 py-3">Nbs d'articles</th>
            <th class="px-4 py-3">Prix de la commande</th>
            <th class="px-4 py-3">Status</th>
            <th class="px-4 py-3">Créé le</th>
            <th class="px-4 py-3"></th>
          </tr>
        </thead>
        <tbody class="bg-white">
          <% orders.each do |order| %>
          <tr class="text-gray-700">
            <td class="px-4 py-3 text-ms font-semibold border">
              <%= link_to "##{order.id[0,7].upcase}" %>
            </td>
            <td class="px-4 py-3 border">
              <div class="flex items-center text-sm">
                <div class="relative w-8 h-8 mr-3 rounded-full md:block">
                  <%= order.cart.user.first_name %> <%= order.cart.user.last_name %>
                </div>
              </div>
            </td>
            <td class="px-4 py-3 text-xs border">
              <%= order.cart.line_items.size %>
            </td>
            <td class="px-4 py-3 text-sm border">
              <%= number_with_delimiter( order.cart.total_price, :delimiter => '.') %> FCFA
            </td>
            <td class="px-4 py-3 text-sm border">
              <% if order.state == "cancelled" %>
                <span class="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-sm">
                  annulée
                </span>
              <% end %>
              <% if order.state == "validated" %>
                <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm">
                  validée
                </span>
              <% end %>
              <% if order.state == "waiting" %>
                <span class="px-2 py-1 font-semibold leading-tight text-gray-700 bg-gray-100 rounded-sm">
                  en attente
                </span>
              <% end %>
            </td>
            <td class="px-4 py-3 text-sm border">
              <%= order.created_at.strftime("%d/%m/%Y") + " à " + order.created_at.strftime("%H:%M") %>
            </td>
            <td class="px-4 py-3 text-sm border">
            <% if params[:store_id] %>
              <%= link_to "Détails", store_order_path(order.cart.store, order) %>
            <% end %>
            <% if params[:user_id] %>
              <%= link_to "Détails", user_order_path(order.cart.user, order) %>
            <% end %>
            </td>
          </tr>          
        <% end %>
        </tbody>
      </table>
</div>

app/views/shared/_product.html.erb
<div class="max-w-xs rounded-xl shadow-lg">
   <div class="w-full h-48 bg-black">
    <% if product.product_background.persisted? %>
      <%= image_tag product.product_background, class: 'h-48 w-full' %>
    <% end %>
  </div>
    <div class="px-6 py-4">
      <h4 class="mb-3 text-xl font-semibold tracking-tight text-gray-800">
        <%= product.name %>
        <% if current_user == product.user %>
          <span class="btn-elementary bg-green-500"><%= link_to 'Edit', edit_user_product_path(current_user, product) %></span>
        <% end %>
      </h4>
      <h4 class="mb-3 text-md font-semibold tracking-tight text-gray-800">
        <%= number_with_delimiter(product.price, :delimiter => '.') %> FCFA
      </h4>
      <p class="leading-normal text-gray-700"><%= product.description %></p>
      <% product.categories.each do |category| %>
    <span class="btn-elementary"><%= link_to "#{category.name}", category_path(category) %></span>
  <% end %>
  <p class="mt-3">
    <%= link_to 'Details', user_product_path(product.user, product), class: 'btn-primary' %>
  </p>
    </div>
</div>

app/views/shared/_rate_product.html.erb
<%= form_with model: [current_user, store, product, product.ratings.build] do |form| %>

  <div>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :store_id, value: store.id %>
    <%= form.label :rates %><br>
    <%= form.select :rates,  [['1', 1],['2', 2],['3', 3],['4', 4],['5', 5]]%>
  </div>
  <%= form.submit submit %>
<% end %> 

app/views/shared/_store_orders.html.erb
<% if orders %>
  <%= render partial: "shared/order_table", locals: { orders: orders } %>
<% end %>

app/views/shared/_top_offer.html.erb
<% top_offer.each do |offer| %>
    <h2 class="text-2xl font-bold text-center my-5">Dernière offre gagnante : 
      <% if offer.user == current_user %>
        <%= offer.user.email %> 
      <% end %>
      <span class="text-red-600"><%= number_with_delimiter( offer.amount, :delimiter => '.') %> XOF</span>
    </h2>
  <% end %>

app/views/shared/_user_orders.html.erb
<% if orders %>
  <%= render partial: "shared/order_table", locals: { orders: orders } %>
<% end %>