config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get "users/signin", to: "users/sessions#new", as: :new_user_session_path
  end
  mount Notifications::Engine => "/notifications"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  else
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  
  get 'products', to: 'products#index'
  get 'products/:id', to: 'products#show', as: 'product'
  get 'products/:id/like', to: 'products#like', as: 'like'
  # get '/stores/:store_id/products/:id', to: 'products#show', as: 'product'
  get 'products/categories/:id', to: 'categories#show', as: 'category'
  
  get 'orders', to: 'orders#index'
  
  resources :carts, only: [:index, :destroy]
  resources :tendances
  resources :users do
    resources :accounts do
      resources :transactions
    end
    resources :favorites
    resources :orders, only: [:index]
    resources :chats do
      resources :messages
    end
    resources :orders, only: [:index, :show, :destroy]
    resources :carts, only: [:index, :destroy] do
      resources :orders, only: [:create, :destroy]
    end
  end
  resources :stores do
    resources :orders, only: [:index, :show, :update, :destroy]
    resources :comments
    resources :chats do
      resources :messages
    end
    resources :products do
      resources :stocks
      resources :line_items, only: [:create]
      resources :bids, except: [:edit] do
        resources :offers, only: [:new, :create, :edit, :update]
      end
      resources :comments
    end
  end

  #Historic of offers by user
  get 'profile/:user_id/offers' => "offers#historic", as: "user_offers_historic"
  #Details of offers by user
  get 'profile/:user_id/offers/:id' => "offers#details", as: "user_offers_offer_historic_details"
  
  # For historic of bids
  get '/stores/:store_id/bids/' => "bids#historic", as: "store_bids_historic"
  # For historic of bid details
  get '/stores/:store_id/bids/:id' => "bids#details", as: "store_bids_bid_historic_details"

  # get '/stores/:store_id/products/:id', to: 'products#show'
  get 'bids', to: 'bids#index'

  # Validate/Reject order
  put 'stores/:store_id/orders/:id/validated' => "orders#validate_order", as: "validate_order"
  put 'stores/:store_id/orders/:id/rejected' => "orders#reject_order", as: "reject_order"
  
  resources :line_items, only: [:create]
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  delete 'line_items/:id' => "line_items#destroy", as: "line_item_delete"
  resources :profiles, only: %i[show edit update]

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      if current_user.first_name == nil && current_user.town == nil && current_user.city == nil
        redirect_to edit_profile_path(current_user)
      end 
    end
    if params[:name]
      redirect_to products_path(name: params[:name])
    end
    @products = Product.all.includes(:store).sort_by {rand}[0,8]
    @tendance = Tendance.order(created_at: :desc).first
    @stores = Store.all.includes(:user).sort_by {rand}[0,4]
    @product_tendances = Product.all.includes(:store).reject{|product| @products.include?(product)}.sort_by {rand}[0,4]
  end

  private

  def products_rand
    @articles = articles.all
    offset = rand(100)
    @products_rand = Product.offset(offset).limit(8)
    
  end

  # def tendances
  #   first_cat = []
  #   product = nil
  #   second_cat = Rating.includes(:product).where('rates > ?', 3).order(rates: :desc).take(10)
  #   if second_cat.length >1
  #     product = second_cat.sample.product
  #   else
  #     product = Product.all.sample
  #   end
  #   Tendance.create(id:product.id, start_time:Time.now, end_time:Time.now)
  #   # third_cat = Order.all.where('rates')

  # end
end

app/views/home/_pre_footer.html.erb
<div class="py-3">
  <p class="text-4xl text-medium text-center">Comment commandez?</p>
  <div class="flex justify-evenly px-10 pt-8">
    <i class="fab fa-affiliatetheme text-6xl"></i>
    <i class="fab fa-amazon-pay text-6xl"></i>
    <i class="fab fa-angrycreative text-6xl"></i>
  </div>
</div>

app/views/home/_product.html.erb
<div class="mb-16">
  <a href='<%= product_path(product) %>' class="w-full h-full">
    <div class="h-64 w-full overflow-hidden">
      <% if product.product_backgrounds.attached? %>
        <%=image_tag product.product_backgrounds[0], class:'h-64 w-full object-cover'%>
      <%else%>
        <%=image_tag 'default_product_image.png', class:'h-64 w-full object-cover'%>
      <% end %>
    </div>
    <div class="py-2 flex items-center justify-between pr-3 pl-1 overflow-hidden">
      <div class="w-32  ">
        <p class=" font-medium text-lg"><%=product.name%></p>
        <p class=" font-normal text-sm py-1"><%=number_with_delimiter(product.price, :delimiter => '.')%> FCFA</p>
      </div>
      <%if product.store.user != current_user%>
        <div class="w-2/5">
          <%if current_user %>
            <a href="<%= store_product_line_items_path(product.store, product) %>" data-method="POST" class="px-5 py-2 bg-red-600 text-white">
              Acheter
            </a>
          <% else %>
            <a href="<%= new_user_session_path %>" class="px-5 py-2 bg-red-600 text-white">
              Acheter
            </a>
          <% end %>
        </div>
      <% end %>
    </div>
  </a>
</div>

app/views/home/_searchs.html.erb
<style>
.w-95{
  width: 92%;
}
.w-5s{
  width: 8%;
}
</style>

<div class="block mb-5" >
  <%= form_with url:root_path, method: 'GET' do |form| %>
    <div class='flex w-full justify-between bg-gray-200 rounded overflow-hidden'>
      <%= form.text_field :name, placeholder:"Search...",class:"w-95 py-2 px-4 bg-transparent outline-none text-black", data:{'search-target': 'name'}, value: params[:name] ? params[:name]: '' %>
      <button type="submit" class=" bg-red-600 w-5s outline-none text-white">
        <i class="fal fa-search"></i>
      </button>
    </div>
  <% end %>
</div>

app/views/home/_stores.html.erb
<a href="<%= store_path(stores)%>" class="mx-2 w-64 m-2">
  <% if stores.background.persisted? %>
    <%= image_tag stores.background, class:'object-cover  h-64 w-full '%>
  <%else%>
    <%=image_tag 'App-Store.jpg', class:'h-64 w-full object-cover'%>
  <% end %>
  <div class="py-2">
    <p class=" font-medium text-md">owner: <%=stores.user.email%></p>
    <p class=" font-semibold text-xl py-2"><%=stores.name%></p>
  </div>
</a>

app/views/home/_tendances.html.erb
<div class="flex overflow-hidden justify-evenly items-stretch px-16 py-10 h-96 bg-gray-100">
  <div class="w-3/5 flex flex-wrap content-center px-5 ">
    <p class="text-6xl w-full"><%=tendance.product.name%></p>
    <p class="font-light w-full py-5 pr-5">
      <%=tendance.product.description%></p>
    </p>
    <p class="text-4xl font-semibold w-full"><%=number_with_delimiter(tendance.product.price, :delimiter => '.')%> FCFA</p>
    <div class="flex py-5">
      <%if current_user %>
        <a href="<%= store_product_line_items_path(tendance.product.store, tendance.product) %>" data-method="POST" class='py-3 px-10 bg-red-600 text-white font-semibold text-lg'> 
          Ajouter au panier
        </a>
      <% else %>
        <a href="<%= new_user_session_path %>" class='py-3 px-10 bg-red-600 text-white font-semibold text-lg'> 
          Ajouter au panier
        </a>
      <% end %>
    </div>
  </div>
  <div class="flex overflow-hidden justify-center items-center w-2/5">
    <% if tendance.product.product_backgrounds.attached? %>
      <%= image_tag tendance.product.product_backgrounds[0], class:'m-0 rounded-full h-72 w-72 '%>
    <%else%>
      <%= image_tag 'default_product_image.png', class:'m-0 rounded-full h-72 w-72 '%>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<% if @tendance %>
  <%=render  partial: 'tendances', locals:{tendance: @tendance}%>
<% end %>

<div class="px-10 pt-5">
  <p class="text-3xl font-medium mt-16"> Produits les plus populaires</p>
  <div class="grid grid-cols-4 gap-3 mt-4">
    <% if @products %>
      <%=render partial: 'product', collection: @products%>
    <% end %>
  </div>
</div>

<div class="px-10 pt-5">
  <p class="text-3xl font-medium mt-16"> Shopper par store</p>
  <div class="grid grid-cols-4 gap-3 mt-4">
    <% if @stores %>
      <%=render partial: 'stores', collection: @stores%>
    <% end %>
  </div>
</div>

<div class="px-10 pt-5">
  <p class="text-3xl font-medium mt-16"> Produits tendances </p>
  <div class="grid grid-cols-4 gap-3 mt-4">
    <% if @stores%>
      <%=render partial: 'product', collection: @product_tendances%>
    <% end %>
  </div>

  <div>
    <%=render 'pre_footer'%>
  </div>
</div>

<% content_for :banners do %>
  <% content_for :search_bar do %>
    <%=render partial: 'searchs'%>
  <% end %>
  <%=render 'shared/banners'%>
<% end %>

<% content_for :footer do %>
  <%=render 'shared/footer'%>
<% end %>






















<%#= link_to 'Sign Out', destroy_user_session_path, method: :delete %>




<%#=render 'product'%>
<%# <h2>Bienvenue sur Jokou !</h2> %>
<%# <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"> %>
  <%# if current_user %>
    <%#= link_to 'Add a Store', new_user_store_path(current_user)%>
  <%# end %>
  <%#= link_to 'Sign in', new_user_session()%>
<%# </button> %>